myshop/myshop/urls.py
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', views.login, {'extra_context': {'next':'/'}}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/logged_out/'}, name='logout'),
    url(r'^logout-then-login/$', views.logout_then_login, name='logout_then_login'),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        

myshop/shop/urls.py
from django.conf.urls import url
from . import views
from . import analysis_controller_views

urlpatterns = [
    url(r'^get_train_pct/(?P<slider_id>[-\w]+)/$', views.get_train_pct, name='get_train_pct'),
    url(r'^get_dropdown_hist/(?P<dropdown_id>[-\w]+)/$', views.get_dropdown_hist, name='get_dropdown_hist'),
    # Generic Result Handler
    url(r'^ajax_handler/(?P<trigger_controller_id>[-\w]+)/$', analysis_controller_views.ajax_handler, name='ajax_handler'),
    url(r'^handle_heatmap/(?P<name>[-\w]+)/$', views.handle_heatmap, name='handle_heatmap'),
    url(r'^analysis_controller/(?P<analysis_controller_id>[-\w]+)/$', analysis_controller_views.analysis_controller_detail, name='analysis_controller_detail'),
    url(r'^analysis_detail/(?P<analysis_id>[-\w]+)/$', views.run_detail, name='analysis_detail'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^addrun/$', views.run_add, name='run_add'),
    url(r'^add/$', views.product_add, name='add'),
    url(r'^dataset/(?P<dataset_id>[-\w]+)/$', views.dataset_detail, name='dataset_detail'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^dataview/(?P<dataview_id>[-\w]+)/$', views.dataview_detail, name='dataview_detail'),
]

myshop/shop/forms.py
from django.forms import ModelForm
from shop.models import DataView, Run

class DataViewForm(ModelForm):
    class Meta:
        model = DataView
        fields = '__all__'

class RunForm(ModelForm):
    class Meta:
        model = Run
        fields = '__all__'

myshop/shop/controllers/analysis_controllers.py
###
### controller_id - an ID for a column filter control
### new_select_state - changes the new select state from the current select state
def column_filter(controller_id, new_select_state)
    #### raise error if not a column filter type
    

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, DataSet, DataView, Run, Slider, Panel, Analysis, Accordion, Dropdown, Controller
from django.contrib.auth.decorators import login_required
import numpy as np
from sklearn import datasets, linear_model
import pandas as pd
from .forms import DataViewForm, RunForm
from django.contrib import messages
from django.http import HttpResponse
import json
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import mpld3
import seaborn as sns
from django.core import serializers
from django.http import JsonResponse
import shop.models
from django_pandas.io import read_frame

@login_required
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    datasets = None
    datasets = DataSet.objects.all()
    dataviews = DataView.objects.all()
    analyses = Analysis.objects.all()
    return render(request, 'shop/product/list.html', {'datasets': datasets, 'dataviews': dataviews, 'analyses': analyses})

@login_required
def product_add(request, category_slug=None):
    if request.method == 'POST':
        form = DataViewForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_dataview = DataView()
            new_dataview.dataset = cd['dataset']
            new_dataview.name = cd['name']
            new_dataview.parameters = cd['parameters']
            new_dataview.row_range_low = cd['row_range_low']
            new_dataview.row_range_high = cd['row_range_high']
            new_dataview.save()
            messages.success(request, 'Data View Successfully Added')
            form = DataViewForm()
    else:
        form = DataViewForm()
    datasets = None
    datasets = DataSet.objects.all()
    return render(request, 'shop/product/add.html', {'datasets': datasets, 'form': form})

@login_required
def dataview_detail(request, dataview_id):
    dataview = get_object_or_404(DataView, pk=dataview_id)
    dataset = dataview.dataset
    #datacode = dataview.dataset.code
    #exec "ds = " + datacode
    #inputs, outputs, ds = get_df(ds)
    #assumes format in load datasets from scikit learn
    #column_filter = dataview.parameters
    #row_range_low = dataview.row_range_low
    #row_range_high = dataview.row_range_high
    #inputs, outputs, ds = get_tf_ds(ds, row_range_low, row_range_high, column_filter)
    #dataviewhtml = ds.to_html()
    evaluated_dataview = pd.read_pickle('dataset/{}'.format(dataset.code))
    for transformation in dataview.transformations.all():
        if transformation.type == "to_datetime":
            feature_name=transformation.feature
            evaluated_dataview.loc[:, feature_name] = pd.to_datetime(evaluated_dataview.loc[:, feature_name], format='%Y%m%d')
        if transformation.type == "column_subset":
            columns = transformation.feature
            exec "evaluated_dataview = "+columns
        if transformation.type == "to_numeric":
            feature_name=transformation.feature
            evaluated_dataview.loc[:, feature_name] = pd.to_numeric(evaluated_dataview.loc[:, feature_name])
    datahtml = evaluated_dataview.head(50).to_html()
    datatypes = pd.DataFrame(evaluated_dataview.dtypes).to_html()
    evaluated_dataview.to_pickle("dataview/{}".format(dataview_id))
    return render(request, 'shop/product/detail.html', {'dataview': dataview, 'datavalues': datahtml, 'datatypes': datatypes})

@login_required
def dataset_detail(request, dataset_id):
    dataset = get_object_or_404(DataSet, pk=dataset_id)
    DataSetModel = getattr(shop.models, dataset.code)
    qs = DataSetModel.objects.all()
    df = read_frame(qs)
    df.to_pickle("dataset/{}".format(dataset.code))
    datahtml = df.to_html()
    return render(request, 'shop/dataset/detail.html', {'dataset': dataset, 'datavalues': datahtml})

@login_required
def run_add(request):
    if request.method == 'POST':
        form = RunForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_run = Run()
            new_run.name = cd['name']
            new_run.train_dv = cd['train_dv']
            new_run.test_dv = cd['test_dv']
            new_run.formula = cd['formula']
            new_run.save()
            messages.success(request, 'Run Successfully Added')
            form = RunForm()
    else:
        form = RunForm()
    datasets = DataSet.objects.all()
    return render(request, 'shop/product/add_run.html', {'datasets': datasets, 'form': form})

@login_required
def run_detail(request, analysis_id):
    analysis = get_object_or_404(Analysis, id=analysis_id)
    #run, inputs, outputs, ds = get_ds(name, 100)
    panels = Panel.objects.all()
    sliders = Slider.objects.all()
    dropdowns = Dropdown.objects.all()
    controllers = Controller.objects.all()
    #coeff, fig_html = calculate_chart(inputs, outputs, ds, 1)
    dataview = analysis.data_view
    dataview_df = pd.read_pickle('dataview/{}'.format(dataview.id))
    return render(request, 'shop/product/run_detail.html', {'sliders': sliders, 'analysis': analysis, 'dataview_df': dataview_df, 'dropdowns': dropdowns, 'controllers': controllers})

def get_df(ds):
    #assumes format in load datasets from scikit learn
    inputs = pd.DataFrame(ds.data)
    outputs = pd.DataFrame(ds.target)
    ds = pd.concat([inputs, outputs], axis=1)
    inputs.columns = ['Age', 'Sex', 'Body Mass Index', 'Average Blood Pressure', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6']
    outputs.columns = ['Target']
    ds.columns = ['Age', 'Sex', 'Body Mass Index', 'Average Blood Pressure', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'Target']
    return (inputs, outputs, ds)

def get_tf_ds(inputs, outputs, ds, row_range_low, row_range_high, column_filter):
    if str(row_range_low)=='':
        row_range_low = 0
    if str(row_range_high)=='':
        row_range_high = 0
    #apply row filter to both inputs and outputs
    inputs = inputs[int(eval(str(row_range_low))):int(eval(str(row_range_high)))]
    outputs = outputs[int(eval(str(row_range_low))):int(eval(str(row_range_high)))]
    #apply column filter
    inputs = inputs[eval(str(column_filter))]
    return (inputs, outputs, ds)

#Request Manager
#1) Map request variables from request
#2) Update the current value of all model objects
#3)
def get_train_pct(request, slider_id):
    if request.method == 'GET':
        response_dict = request.GET
        #test = str(int(slider_id))
        #for key in request.GET.iterkeys():
        #response_data[key] = request.GET.getlist(key)
        #response_data['risk_threshold'] = str(int(risk_threshold*100))
        #run, inputs, outputs, ds = get_ds(name, train_pct)
        #coeff, response_data['result_html'] = calculate_chart(inputs, outputs, ds, risk_threshold)
        test_value = test_func(slider_id, response_dict)
        return HttpResponse(json.dumps(test_value), content_type = "application/json")

def test_func(slider_id, response_dict):
    slider = Slider.objects.get(pk=slider_id)
    panel = slider.parent
    current_value = response_dict.get("slider_{}".format(slider_id))
    return int(current_value)**2

def get_dropdown_hist(request, dropdown_id):
    if request.method == 'GET':
        response_dict = request.GET
        #test = str(int(slider_id))
        #for key in request.GET.iterkeys():
        #response_data[key] = request.GET.getlist(key)
        #response_data['risk_threshold'] = str(int(risk_threshold*100))
        #run, inputs, outputs, ds = get_ds(name, train_pct)
        #coeff, response_data['result_html'] = calculate_chart(inputs, outputs, ds, risk_threshold)
        test_value = hist_func(dropdown_id, response_dict)
        return HttpResponse(json.dumps(test_value), content_type = "application/json")

def hist_func(dropdown_id, response_dict):
    dropdown = Dropdown.objects.get(pk=dropdown_id)
    dataview = dropdown.panel.accordion.analysis.data_view
    dataview_df = pd.read_pickle('dataview/{}'.format(dataview.id))
    current_value = response_dict.get("dropdown_{}".format(dropdown_id))
    fig, ax = plt.subplots()
    x = np.array(dataview_df[current_value])
    ax.hist(x, 50, normed = 1, alpha = 0.5)
    ax.set_xlabel(current_value)
    ax.set_title(current_value + ' Histogram')
    ax.set_xlim(0, 1.01*max(x))
    fig_html = mpld3.fig_to_html(fig)
    return fig_html

def handle_heatmap(request, name):
    response_data = {}
    if request.method == 'GET':
        run, inputs, outputs, ds = get_ds(name, "100")
        response_data['heatmap_html'] = get_heatmap(ds)
        return HttpResponse(json.dumps(response_data), content_type = "application/json")

def calculate_chart(inputs, outputs, ds, risk_threshold):
    plt.close('all')
    regr = linear_model.LinearRegression()
    regr.fit(inputs, outputs)
    coeff = regr.coef_
    fig, ax = plt.subplots()
    risk_colors = get_colors(inputs, outputs, risk_threshold)
    ax.scatter(inputs, outputs, color=risk_colors)
    ax.set_title("Linear Risk Plot", fontsize=32)
    ax.set_xlabel("Age", fontsize=16)
    ax.set_ylabel("HbA1c Year 2", fontsize=16)
    ax.plot(inputs, regr.predict(inputs), color="blue", linewidth=3)
    fig_html = mpld3.fig_to_html(fig)
    return (coeff, fig_html)

def get_ds(name, train_pct):
    run = get_object_or_404(Run, name=name)
    train_dv = get_object_or_404(DataView, name=run.train_dv.name)
    datacode = train_dv.dataset.code
    exec "ds = " + datacode
    inputs, outputs, ds = get_df(ds)
    column_filter = train_dv.parameters
    row_range_low = train_dv.row_range_low
    row_range_high = train_dv.row_range_high
    #train_pct override
    if train_pct:
        row_range_low = 1
        row_range_high = train_pct
    inputs, outputs, ds = get_tf_ds(inputs, outputs, ds, row_range_low, row_range_high, column_filter)
    return (run, inputs, outputs, ds)

def get_colors(inputs, outputs, risk_threshold):
    risk_level = outputs.quantile(risk_threshold)
    risk_colors = []

myshop/shop/templates/shop/product/add.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
	{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Data Sets</h3>
        <ul>
            <li {% if not dataset %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All Data Sets</a>
            </li>
                {% for dataset in datasets %}
                <li>
                    <a href="{{ dataset.get_absolute_url }}">{{ dataset.name }}</a>
                </li>
                {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <div class="product-list">
            <h1>Add Data View</h1>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <p><input type='submit' value='submit'></p>
            </form>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/add_run.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
	{% if category %}{{ category.name }}{% else %}Runs{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Data Sets</h3>
        <ul>
            <li {% if not dataset %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All Data Sets</a>
            </li>
                {% for dataset in datasets %}
                <li>
                    <a href="{{ dataset.get_absolute_url }}">{{ dataset.name }}</a>
                </li>
                {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <div class="product-list">
            <h1>Add Run</h1>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <p><input type='submit' value='submit'></p>
            </form>
        </div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.title }}{% else %}Data View{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="product-detail">
        <h3>Name: {{ dataview.name }}</h3>
        <h3>Dataset: {{ dataview.dataset }}</h3>
        <h3>Transformations:</h3>
        {% if dataview.transformations %}
            <ol>
                {% for transformation in dataview.transformations.all %}
                    <li>{{ transformation.name }}</li>
                {% endfor %}
            </ol>
        {% endif %}
        <h3>Data Types:</h3>
        {{ datatypes|safe }}
        <h3>Preview:</h3>
        {{ datavalues|safe }}
    </div>
</div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
	{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
        <h1>Data Sets</h1>
        <ul>
            {% for dataset in datasets %}
            <li>
                <a href="{{ dataset.get_absolute_url }}">{{ dataset.name }}</a>
            </li>
            {% endfor %}
        </ul>
            <div id="main" class="product-list">
                <div class="product-list">
                    <h1>Data Views</h1>
                        <ul>
                            {% for dataview in dataviews %}
                                <li><a href="{{ dataview.get_absolute_url }}">{{ dataview.name }}</a></li>
                            {% endfor %}
                        </ul>
                </div>
            </div>
        <div id="main" class="product-list">
            <div class="product-list">
                <h1>Analyses</h1>
                    <ul>
                        {% for analysis in analyses %}
                        <li><a href="{{ analysis.get_absolute_url }}">{{ analysis.title }}</a></li>
                        {% endfor %}
                    </ul>
            </div>
    </div>
</div>
{% endblock %}

myshop/shop/templates/shop/product/run_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Analysis{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <br>
        {% for accordion in analysis.analysis_accordions.all %}
        <div class="row">
            {% if forloop.counter == 1 %} <!-- Analysis controllers -->
                <div class="col-md-3">
                    <div class="well">
                        <div class="form-group">
                            <label for="sel1"><div style="border:0; color:#f6931f; font-weight:bold;"></div></label>
                            <select class="form-control" id="sel1">
                            </select>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="col-md-3"></div>
            {% endif %}
        <div class="col-md-9">
            <h4>{{ accordion.title }}</h4>
            <div id="accordion_{{ accordion.id }}" class="panel panel-default">
                {% for panel in accordion.accordion_panels.all %}
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-target="{{ panel.panel_body_target_id }}">
                                {{ panel.title }}
                                <span class="fa fa-chevron-up pull-right"></span>
                            </a>
                        </h4>
                    </div>
                    <div id="{{ panel.panel_body_id }}" class="panel-collapse collapse in">
                        <div class="row">
                            <div class="col-md-9">
                                <div id="panel_result_{{ panel.id }}"></div>
                                <!-- <div id="test_viz"></div> -->
                            </div>
                            <div class="col-md-3">
                                <div class="well">
                                    {% for controller in panel.controllers.all %}
                                        {% if controller.type = "slider" %}
                                        <div id="controller_label_{{ controller.id }}" style="border:0; color:#f6931f; font-weight:bold;">{{ controller.variable }}</div>
                                            <br>
                                            <div id="controller_{{ controller.id }}" class="slider-controller"></div>
                                            <br>
                                        {% elif controller.type = "single_dropdown" %}
                                            <div id="controller_label_{{ controller.id}}" style="border:0; color:#f6931f; font-weight:bold;">{{ controller.variable }}</div>
                                            <br>
                                            <select id="controller_{{ controller.id }}" class="singledropdown-controller">
                                            {% for column in dataview_df.columns %}
                                                <option value="{{ column }}">{{ column }}</option>
                                            {% endfor %}
                                            </select>
                                            <br>
                                        {% elif controller.type = "multiple_dropdown" %}
                                            <div id="controller_label_{{ controller.id }}" style="border:0; color:#f6931f; font-weight:bold;">{{ controller.variable }}</div>
                                            <br>
                                            <select multiple id="controller_{{ controller.id }}" data-placeholder="Choose {{ controller.variable }}" class="chosen-select multiple-dropdown-controller">
                                            {% for column in dataview_df.columns %}
                                                <option value="{{ column }}">{{ column }}</option>
                                            {% endfor %}
                                            </select>
                                            <br>
                                        {% else %}
                                            <p> Unrecognized controller type </p>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div><!-- end row -->
                    </div><!-- end panel body-->
                {% endfor %}
                </div>
            </div>  
    </div> <!-- end row -->
    {% endfor %}
</div>
<script>
    $(function() {
          {% for controller in controllers %}
            {% if controller.type = 'slider' %}
                    $( '#controller_{{ controller.id }}' ).slider({
                                                           value: {{ controller.default_value }},
                                                           min: {{ controller.min }},
                                                           max: {{ controller.max }},
                                                           step: {{ controller.step }},
                                                           stop: function( event , ui ){
                                                            $( '#controller_label_{{ controller.id }}' ).html( '{{ controller.variable }}'.concat(": ", $( this ).slider("value")) );
                                                           $.ajax({
                                                                  url: "{% url 'shop:ajax_handler' controller.id %}",
                                                                  data: createJSON(),
                                                                  success: function(result){
                                                                    $( "#panel_result_{{ controller.panel.id }}" ).html( result );
                                                                  }
                                                                  });
                                                           }
                                                  });
            {% elif controller.type = 'single_dropdown' %}
                    $( '#controller_{{ controller.id }}' ).selectmenu({
                                                    style: 'dropdown',
                                                    change: function(event, data){
                                                        $( '#controller_label_{{ controller.id }}' ).html( '{{ controller.variable }}'.concat(": ", $( this ).val()) );
                                                    $.ajax({
                                                           url: "{% url 'shop:ajax_handler' controller.id %}",
                                                           data: createJSON(),
                                                           success: function(result){
                                                           $( "#panel_result_{{ controller.panel.id }}" ).html( result );
                                                           }
                                                           });
                                                    }
                        
                                                    });
            {% elif controller.type = 'multiple_dropdown' %}
                    $( '#controller_{{ controller.id }}' ).selectable({
                                                        stop: function(event, data){
                                                        $( '#controller_label_{{ controller.id }}' ).html( '{{ controller.variable }}'.concat(": ", $( this ).val()) );
                                                        $.ajax({
                                                               url: "{% url 'shop:ajax_handler' controller.id %}",
                                                               data: createJSON(),
                                                               success: function(result){
                                                               $( "#panel_result_{{ controller.panel.id }}" ).html( result );
                                                               }
                                                               });
                                                        }
                                                        
                                                        });
            {% endif %}
      {% endfor %}
      //result = Viz('digraph Tree { node [shape=box]; 0 [label="X[1] <= 0.5\nentropy = 0.2724\nsamples = 66773\nvalue = [63652, 3121]"] ; 1 [label="X[2] <= 0.5\nentropy = 0.2706\nsamples = 66741\nvalue = [63649, 3092]"] ; 0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;}');
      //$( '#test_viz' ).html( result );
      $(".chosen-select").chosen();
    });
</script>
<script>
    $(function() {
        {% for accordion in analysis.analysis_accordions.all %}
      $( "#accordion_{{ accordion.id }}" ).accordion({
                                  active: false,
                                  collapsible: true,
                                  heightStyle: "content"
                                                     });
      {% endfor %}
});
</script>
<script>
function createJSON() {
    jsonObj = {};
    $(".slider-controller").each(function() {
        var id = $(this).attr("id");
        var value = $(this).slider("value");
        jsonObj[id]=value;
    });
    $(".singledropdown-controller").each(function() {
        var id = $(this).attr("id");
        var value = $(this).val();
        jsonObj[id]=value;
    });
    $(".multiple-dropdown-controller").each(function() {
        var id = $(this).attr("id");
        var value = $(this).val();
        jsonObj[id]=value;
    });
    return jsonObj;
    }
</script>
{% endblock %}